In [1]:
import numpy as np

In [60]:
a = np.array([[1,2],[3,4], [5,6]])
b = np.array([[[1, 2],[3,4]], [[5,6],[7,8]]])
correct_answer = np.array([[7,10], [43,50]])

In [9]:
a @ b

array([[[ 7, 10],
        [15, 22]],

       [[19, 22],
        [43, 50]]])

In [25]:
c = np.array([1,2])
d = np.array([[1, 2],[3,4]])
c @ d

array([ 7, 10])

In [14]:
e = np.array([3,4])
d = np.array([[5, 6],[7,8]])
e @ d

array([43, 50])

In [53]:
np.tensordot(a,b,axes=(1,1))

array([[[ 7, 10],
        [19, 22]],

       [[15, 22],
        [43, 50]]])

In [54]:
c.T @ d

array([ 7, 10])

In [57]:
np.diagonal(a @ b).T

array([[ 7, 10],
       [43, 50]])

In [63]:
f = np.array([[5,6],[7,8], [8,9]])
a.shape,f.shape

((3, 2), (3, 2))

In [131]:
np.einsum('ij,ij->i', a, f)

array([17, 53, 94])

In [115]:
np.linalg.multi_dot([a,f.T])

array([[17, 23, 26],
       [39, 53, 60],
       [61, 83, 94]])

In [133]:
a[:, :, np.newaxis] @ f[:, np.newaxis]

array([[[ 5,  6],
        [10, 12]],

       [[21, 24],
        [28, 32]],

       [[40, 45],
        [48, 54]]])

In [13]:
import torch
from torch.autograd import Variable

In [144]:
idx = torch.tril_indices(2, 2)

In [47]:
a = np.array([[1,2],[3,4]])
a = torch.FloatTensor(a)
vec = torch.FloatTensor([[1,2,3,4], [5,6,7,8]])
vec1 = vec.view(-1,2,2)

In [48]:
tril_mask = Variable(torch.tril(torch.ones(
            2, 2), diagonal=-1).unsqueeze(0))

diag_mask = Variable(torch.diag(torch.diag(
            torch.ones(2, 2))).unsqueeze(0))

In [49]:
vec2 = vec1 * tril_mask.expand_as(vec1) + torch.exp(vec1) * diag_mask.expand_as(vec1)
vec2

tensor([[[2.7183e+00, 0.0000e+00],
         [3.0000e+00, 5.4598e+01]],

        [[1.4841e+02, 0.0000e+00],
         [7.0000e+00, 2.9810e+03]]])

In [50]:
vec2.transpose(2,1)

tensor([[[2.7183e+00, 3.0000e+00],
         [0.0000e+00, 5.4598e+01]],

        [[1.4841e+02, 7.0000e+00],
         [0.0000e+00, 2.9810e+03]]])

In [51]:
action = torch.FloatTensor([[1,2], [3,4]])
mu = torch.FloatTensor([[3,5], [5,6]])
action_mu = (action - mu).unsqueeze(2)

In [57]:
q =torch.bmm(action_mu.transpose(2, 1), vec2)
q

tensor([[[  -14.4366,  -163.7944]],

        [[ -310.8263, -5961.9160]]])

In [65]:
A= -0.5 * torch.bmm(q, action_mu)[:, :, 0]
A

tensor([[ -260.1282],
        [-6272.7422]])

In [66]:
A + torch.FloatTensor([[2],[3]])

tensor([[ -258.1282],
        [-6269.7422]])