In [1]:
import numpy as np

In [60]:
a = np.array([[1,2],[3,4], [5,6]])
b = np.array([[[1, 2],[3,4]], [[5,6],[7,8]]])
correct_answer = np.array([[7,10], [43,50]])

In [9]:
a @ b

array([[[ 7, 10],
        [15, 22]],

       [[19, 22],
        [43, 50]]])

In [25]:
c = np.array([1,2])
d = np.array([[1, 2],[3,4]])
c @ d

array([ 7, 10])

In [14]:
e = np.array([3,4])
d = np.array([[5, 6],[7,8]])
e @ d

array([43, 50])

In [53]:
np.tensordot(a,b,axes=(1,1))

array([[[ 7, 10],
        [19, 22]],

       [[15, 22],
        [43, 50]]])

In [54]:
c.T @ d

array([ 7, 10])

In [57]:
np.diagonal(a @ b).T

array([[ 7, 10],
       [43, 50]])

In [63]:
f = np.array([[5,6],[7,8], [8,9]])
a.shape,f.shape

((3, 2), (3, 2))

In [110]:
np.einsum('ij,ij->i', a, f)

array([17, 53, 94])

In [115]:
np.linalg.multi_dot([a,f.T])

array([[17, 23, 26],
       [39, 53, 60],
       [61, 83, 94]])

In [130]:
a[:, :,np.newaxis] @ f[:, np.newaxis]

array([[[ 5,  6],
        [10, 12]],

       [[21, 24],
        [28, 32]],

       [[40, 45],
        [48, 54]]])